# 1. Create a 3x3x3 array with random values 

In [7]:
import numpy as np
arr1=np.random.randn(3,3,3)
print(arr1)

[[[ 0.11057026 -0.36346975 -1.43339213]
  [-0.19574477  0.8843948   0.61895114]
  [-0.21416978 -0.34349019  0.79250128]]

 [[ 0.54158506  0.9929864  -0.58103164]
  [-0.41080008  0.71963616  0.68754341]
  [-1.52074232  0.63294778 -2.3280413 ]]

 [[-1.24239694  0.46601804  0.13315484]
  [-0.17828373 -0.22441396 -1.16084438]
  [ 2.84232949  2.33175441 -1.05326222]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [9]:
x=np.diag((1,2,3,4))
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [43]:
import numpy as np
arr = np.ones((8,8))
print("Checkerboard pattern:")
arr= np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [12]:
x=np.eye(5,5,dtype=int)
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# 5.  How to find common values between two arrays?

In [39]:
x=np.arange(25).reshape(5,5)
print(x)
y=np.arange(25).reshape(5,5)
print(np.intersect1d(x, y))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


# 6.How to get the dates of yesterday, today and tomorrow?

In [44]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [22]:
arr1=np.random.randn(3,3)
arr2=np.random.randn(3,3)
compare=(arr1==arr2)
equal_notequal=compare.all()
print(equal_notequal)


False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [36]:
vector=np.random.rand(10)
print(vector)
vector[vector.argmax()]=0
print(vector)

[0.09154904 0.37050426 0.5684531  0.7584745  0.59737812 0.81949267
 0.40572816 0.07434344 0.23484475 0.72612467]
[0.09154904 0.37050426 0.5684531  0.7584745  0.59737812 0.
 0.40572816 0.07434344 0.23484475 0.72612467]


# 9. How to print all the values of an array?

In [29]:
arr=array([1,6,3,9,5,0,5,9,3])
print(arr)

[1 6 3 9 5 0 5 9 3]


# 10.Subtract the mean of each row of a matrix

In [31]:
arr=array([1,6,3,9,5,0,5,9,3])
arr1=arr-arr.mean()
print(arr1)

[-3.55555556  1.44444444 -1.55555556  4.44444444  0.44444444 -4.55555556
  0.44444444  4.44444444 -1.55555556]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [59]:
import numpy as np
x=np.array([1,7,3,8,4,7,4,5,3,9,3,2,8,4,7])
counts = np.bincount(x)
print(np.argmax(counts))

3


# 14.How to get the n largest values of an array

In [61]:
import numpy as np
x = np.arange(10)
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [66]:
arr1=[1,2,3,4,5,6]
arr2=['a','b','c','d','e','f']

In [68]:
result= np.core.records.fromarrays([arr1,arr2],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'a')
(2, 'b')
(3, 'c')
